{{- if .Values.migration.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sample-web-app.fullname" . }}-migration
  labels:
    {{- include "sample-web-app.labels" . | nindent 4 }}
data:
  migrate.sh: |
    #!/bin/sh
    set -e

    echo "Starting database migration..."

    cd /app

    # Run programmatic migration using drizzle-orm (production best practice)
    echo "Running database migration..."
    node -e "
    const { drizzle } = require('drizzle-orm/node-postgres');
    const { migrate } = require('drizzle-orm/node-postgres/migrator');
    const { Pool } = require('pg');

    (async () => {
      if (!process.env.DATABASE_URL) {
        console.error('DATABASE_URL is not set');
        process.exit(1);
      }

      const pool = new Pool({ connectionString: process.env.DATABASE_URL });
      const db = drizzle(pool);

      try {
        await migrate(db, { migrationsFolder: './drizzle' });
        console.log('Migration completed successfully');
      } catch (error) {
        console.error('Migration failed:', error);
        process.exit(1);
      } finally {
        await pool.end();
      }
    })();
    "

    echo "Migration completed successfully"
{{- end }}
