{{- if .Values.migration.runAsJob }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "sample-web-app.fullname" . }}-migration-{{ .Release.Revision }}
  labels:
    {{- include "sample-web-app.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    metadata:
      labels:
        {{- include "sample-web-app.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: migration
    spec:
      restartPolicy: Never
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: migration
        {{- if .Values.migration.image }}
        image: {{ .Values.migration.image }}
        {{- else }}
        image: {{ include "sample-web-app.image" . }}
        {{- end }}
        command: ['/bin/sh']
        args: ['/migration/migrate.sh']
        env:
        {{- if .Values.migration.env }}
        {{- toYaml .Values.migration.env | nindent 8 }}
        {{- else }}
        {{- with .Values.env }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- end }}
        volumeMounts:
        - name: migration-script
          mountPath: /migration
        workingDir: /app
      volumes:
      - name: migration-script
        configMap:
          name: {{ include "sample-web-app.fullname" . }}-migration
          defaultMode: 0755
{{- end }}